### ISSUE TITLE
Using the Console

### ISSUE THREAD

**Issue by Auenc** [boolean-uk/js-browser-intro#1]
I feel like it might be a little odd seeing a code snippet containing HTML and JS when the final sentence of the previous section states:
> Just like with CSS we will always use a separate file as that is considered best practice.

The image displaying the output of the `console.log(people)` wouldn't be what a student would see if they ran this code. In stead it would be something like this (minus the code of course). Might be worth adding a line of text in there to make it clear that the output is clickable.
![Screenshot from 2022-02-03 21-30-49](https://user-images.githubusercontent.com/14826315/152432287-f13b1591-bf21-42ba-8f99-ce50e1e3c123.png)

**Comment by mikemherron** [comment]
Updated
